"""
Segment Verification and Quality Check Module

This module provides utilities to inspect and validate audio segments generated by
the segmentation pipeline. It checks for common quality issues and generates summary
statistics to help identify problems before further processing.

The verification process checks:
- Segment duration (warnings for very short or very long segments)
- Audio format compliance (16kHz sample rate, mono channels)
- File readability and format integrity
- Per-lecture statistics and distribution

Usage:
    python verify_segments.py --segments_dir data/segments

The output includes:
- Overall duration statistics (min, max, mean)
- Duration distribution histogram
- Per-lecture breakdown with segment counts and total duration
- List of any issues found, categorized by severity
"""

import argparse
import torchaudio
from pathlib import Path
from collections import defaultdict


def verify(segments_dir: Path):
    """
    Verify and analyze audio segments for quality and consistency.

    This function scans a directory of audio files and generates a detailed
    quality report. It checks format compliance and identifies potential issues.

    Args:
        segments_dir (Path): Directory containing .wav segment files to verify.

    Output:
        Prints a formatted report to stdout including:
        - Summary statistics (total segments, total duration, min/max/mean lengths)
        - Histogram of duration distribution across predefined buckets
        - Per-lecture breakdown with segment counts
        - List of any detected issues (if any)

    Note:
        - Only processes .wav files
        - Expected format: 16kHz sample rate, mono, WAV codec
        - Warnings are generated for segments outside typical duration range
        - Expected file naming convention: {lecture_name}_seg{NNN}.wav
    """
    # Collect all .wav files in the directory, sorted by name for consistent ordering
    seg_files = sorted(segments_dir.glob("*.wav"))
    if not seg_files:
        print(f"No .wav files found in {segments_dir}")
        return

    print(f"Found {len(seg_files)} segments in {segments_dir}\n")

    # Initialize storage for analysis
    durations = []
    issues = []
    by_lecture = defaultdict(list)

    # Process each segment file
    for f in seg_files:
        try:
            # Load audio metadata using torchaudio
            info = torchaudio.info(str(f))
            duration = info.num_frames / info.sample_rate
            sr = info.sample_rate
            channels = info.num_channels

            # Store duration for statistics
            durations.append(duration)

            # Extract lecture name (everything before the last '_seg' segment indicator)
            lecture_name = "_".join(f.stem.split("_")[:-1])
            by_lecture[lecture_name].append(duration)

            # Quality checks: flag issues based on duration and format
            if duration < 10:
                issues.append(f"  ⚠ Too short ({duration:.1f}s): {f.name}")
            if duration > 75:
                issues.append(f"  ⚠ Too long ({duration:.1f}s): {f.name}")
            # Verify sample rate is the expected 16kHz (standard for speech processing)
            if sr != 16000:
                issues.append(f"  ✗ Wrong sample rate ({sr}Hz): {f.name}")
            # Verify mono audio (single channel)
            if channels != 1:
                issues.append(f"  ✗ Not mono ({channels}ch): {f.name}")

        except Exception as e:
            # Handle files that cannot be read or are corrupted
            issues.append(f"  ✗ Could not read {f.name}: {e}")

    # Print overall duration statistics
    print("── Duration stats ──────────────────────────")
    print(f"  Total segments : {len(durations)}")
    print(f"  Total audio    : {sum(durations)/60:.1f} min")
    print(f"  Mean duration  : {sum(durations)/len(durations):.1f}s")
    print(f"  Min duration   : {min(durations):.1f}s")
    print(f"  Max duration   : {max(durations):.1f}s")

    # Print duration distribution histogram with predefined buckets
    print("\n── Duration distribution ───────────────────")
    bins = [(0, 20), (20, 40), (40, 60), (60, 70), (70, 999)]
    labels = ["<20s", "20–40s", "40–60s", "60–70s", ">70s"]
    for (lo, hi), label in zip(bins, labels):
        # Count segments falling into each duration bucket
        count = sum(1 for d in durations if lo <= d < hi)
        bar = "█" * count  # Visual bar representation
        print(f"  {label:8s} {bar} {count}")

    # Print per-lecture statistics for multi-lecture datasets
    print("\n── Per lecture ─────────────────────────────")
    for lecture, durs in sorted(by_lecture.items()):
        print(f"  {lecture}: {len(durs)} segments, {sum(durs)/60:.1f} min total")

    # Print issues if any were found, otherwise indicate success
    if issues:
        print(f"\n── Issues ({len(issues)}) ────────────────────────")
        for issue in issues:
            print(issue)
    else:
        print("\n✓ No issues found. All segments look good!")


def main():
    """
    Command-line entry point for the segment verification tool.

    Parses command-line arguments and runs the verification function.
    """
    parser = argparse.ArgumentParser(
        description="Verify audio segments for quality and consistency"
    )
    parser.add_argument(
        "--segments_dir",
        type=str,
        default="data/segments",
        help="Directory containing .wav segment files (default: data/segments)",
    )
    args = parser.parse_args()
    verify(Path(args.segments_dir))


if __name__ == "__main__":
    main()
